name: Push to B2
on: [push]
jobs:
  - name: Release site to B2
    uses: mostlytyped/s3-put-action@v1.0.0
    with:
      args: --acl-public
    env:
      LOCAL_FILE: /
      REMOTE_FILE: /
      AWS_ENDPOINT: ${{ secrets.AWS_ENDPOINT }}
      AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}